### ISSUE TITLE
Add documentation page for ResNet

### ISSUE THREAD

**Issue by cgarciae** [poets-ai/elegy#117]
Hey @alexander-g! 

Now that the `RestNet*` architectures are on `master` I think we should add them to the documentation. This is done by adding the `__all__`  constant to `elegy/nets/__init__.py` plus including `"resnet"` in the list, and then adding the `__all__` constant to `elegy/nets/resnet.py` and including all the `"ResNet*"` names.

To run the documentation locally you can execute:

```bash
scripts/run-docs
```
This will compile the documentation with `mkdocs` and spin up a server.

**Comment by alexander-g** [comment]
I get the following error running `scripts/run-docs`

```
Traceback (most recent call last):
  File "scripts/update_docs.py", line 41, in <module>
    docs_info = get(elegy, "elegy")
  File "scripts/update_docs.py", line 35, in get
    for module, name in ((getattr(module, name), name) for name in all_members)
  File "scripts/update_docs.py", line 35, in <dictcomp>
    for module, name in ((getattr(module, name), name) for name in all_members)
  File "scripts/update_docs.py", line 35, in get
    for module, name in ((getattr(module, name), name) for name in all_members)
  File "scripts/update_docs.py", line 26, in <dictcomp>
    outputs = {
  File "scripts/update_docs.py", line 35, in <genexpr>
    for module, name in ((getattr(module, name), name) for name in all_members)
AttributeError: module 'elegy.losses' has no attribute 'MeanSquaredLogarithmicErrormean_squared_logarithmic_errorSparseCategoricalCrossentropy'
```

**Comment by alexander-g** [comment]
The error was due to run-docs using the installed Elegy version instead of the working tree. Setting `PYTHONPATH="./"` solved this
